### ISSUE TITLE
Question: The jobs did not finish in time

### ISSUE THREAD

**Issue by glains** [EvoSuite/evosuite#130]
### Context

During execution, evosuite ran into an error:
```
[main] ERROR JobExecutor - The jobs did not finish in time
```
As a result, over 90% of the jobs scheduled were not executed, which lead to missing tests.

### EvoSuite Arguments

```
mvn evosuite:generate -Dcores=2 -DmemoryInMB=4000
```

### Additional info

My guess is that the servers hardware is simply to bad and the expected completion time did not match the *actual* time needed for the job to finish. The main thread waits one more minute before terminating these jobs. 

If used with better hardware or less resources the error (mostly) disappeared. Could you clarify?

**Comment by realnikunj** [comment]
I am facing this same issue when executing the below command in my base directory -

`mvn compile evosuite:generate -DtimeInMinutesPerClass=6`

Still the tests fail to generate. However, this did work for me just fine last week with the same version (1.0.5).
Even after providing 6 minutes per class, this issue does not go. Please help!

**Comment by fababa** [comment]
Hello guys, 
I encountered the same problem.

Does it have any resolution on this problem?
I tried the following version below but getting the same error:
v1.0.5
v1.0.4
v1.0.3
v1.0.2

Thanks,

**Comment by glains** [comment]
Coming back to this issue, i cannot reproduce it anymore. Using the newest version, 1.0.5, the issue disappeared. Should i close this issue or wait till all other comments are resolved?

**Comment by gofraser** [comment]
Based on the last comment, I assume this is fixed.

**Comment by WesLeeWH** [comment]
i have the same issue as well... not able to generate. zero tests. 

i checked in the target\classes folder, i have all the .class files in the folder. when i run it on a small project like tutorialMaven, it runs okay. when i run it in my own project. it failed.

is there any limitation to how much complexity of the codes it can handle? 

please advise. thank you

**Comment by doyo3141** [comment]
I believe this only happens with using -Duse_separate_classloader=false.

**Comment by sandaliqbal** [comment]
I'm using version 1.0.6 and I'm still getting the same issue. Basically its not able to generate a single unit test for my project. I'm using the following command:

mvn evosuite:generate

This is what I see in the console:

[INFO] === CTG run results ===
[INFO] Removed test suites: 0
[INFO] New test suites: 0
[INFO] Missing classes:
<List of all classes>

Also I dont get to see any informative error. Is there a place where I can see error logs and figure out whats going wrong?

**Comment by gofraser** [comment]
EvoSuite creates a hidden directory `.evosuite`, in there you'll find a subdirectory for each time you run EvoSuite (e.g. `tmp_2018_06_02_21_47_54`). In the `logs` subdirectory you'll find the stdout/stderr output for each class EvoSuite was invoked on. Can you maybe share the log files so I can have a look?

**Comment by sandaliqbal** [comment]
Well there's nothing much in the logs either. Attaching the log files.
[std_err_MASTER.log](https://github.com/EvoSuite/evosuite/files/2066142/std_err_MASTER.log)

By the way when I run the commandline version I do get some test files generated though most of them complain of classnotfound error maybe because of classpath issues.

**Comment by gofraser** [comment]
Is the project you are trying to apply EvoSuite to available somewhere?

**Comment by sandaliqbal** [comment]
I'm afraid not its private project within my organization which cant be shared.

**Comment by gofraser** [comment]
Can you reproduce this behaviour on an example project, or an open source project?

**Comment by sandaliqbal** [comment]
OK I will try to setup a similar project and try to reproduce the issue. In the meanwhile can you tell me how can I give the m2 repository path in the classpath so that I dont get classdefnotfound error while running from command line? I was using this command:

java -jar $EVOSUITE -generateSuite -projectCP "target/classes:$M2_REPO/org/apache/logging/log4j/log4j-1.2-api/2.1/log4j-1.2-api-2.1.jar:$M2_REPO/org/springframework/spring-tx/4.2.6.RELEASE/spring-tx-4.2.6.RELEASE.jar" -prefix com.test.mypackage

But as I cant keep giving path to each and every jar in M2_REPO for some classes it fails with class notfound so I was wondering if I can give the path to entire M2_REPO?

**Comment by sandaliqbal** [comment]
So I copied all maven dependencies under target/dependency and run the following command:

java -jar $EVOSUITE -generateSuite -prefix com.test.package -libraryPath target/dependency/ 

but still some of the classes fail to generate any test because of class not found error whereas that class is there in the jar under target/dependency. Any solution on how to resolve this?

**Comment by gofraser** [comment]
Use `-projectCP` and not `-libraryPath`.

**Comment by sandaliqbal** [comment]
Most of the time getting this exception while generating tests:

TestSuiteFitnessFunction - TG: Exception caught: Unknown Id.generator: myntGenerator
org.evosuite.shaded.org.hibernate.AnnotationException: Unknown Id.generator: myntGenerator
	at org.evosuite.shaded.org.hibernate.cfg.BinderHelper.makeIdGenerator(BinderHelper.java:665) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.shaded.org.hibernate.cfg.BinderHelper.makeIdGenerator(BinderHelper.java:703) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]

**Comment by gofraser** [comment]
Is there more to this stacktrace? I can't really see what context this is happening in.

Also, any luck on creating an example project that lets me reproduce the problem?

**Comment by lamrin13** [comment]
I am also not able to generate any test cases using 1.0.5 and 1.0.6,

I tried with the minimal code in a class for example,

public class MyApp {
	public String getId(Long prefix, String suffix) {
		if (prefix == null) {
			throw new NullPointerException("id must not be null");
		}

		if (suffix == null) {
			return prefix + "--ID--(-)";
		}

		return prefix + "--ID--(" + suffix + ")";
	}
}

And to generate tests I used,
mvn -DmemoryInMB=2000 -Dcores=4 evosuite:generate evosuite:export
mvn -DmemoryInMB=4000 -Dcores=8 -DtimeInMinutesPerClass=10 evosuite:generate evosuite:export
mvn -DmemoryInMB=5000 -Dcores=8 -DtimeInMinutesPerClass=60 evosuite:generate evosuite:export

But still got the same error,
 Going to start job for: com.hascode.tutorial.MyApp. Expected to end in 120 seconds, by 2021-11-02T13:28:07.434
[INFO] [MASTER] 13:29:07.149 [main] ERROR JobExecutor - The jobs did not finish in time
[INFO] * Updating database to com.hascode.tutorial.MyApp
[INFO] === CTG run results ===
[INFO] Removed test suites: 0
[INFO] New test suites: 0
[INFO] WARN: failed to generate tests for com.hascode.tutorial.MyApp
[INFO] Stopping spawn process manager
